export const blogging = [
    {
        id: 1,
        title: "How to view my Portfolio",
        category: "Tech",
        subCategory: ["interview", "ux", "creativity"],
        description: "A portfolio website is a unique way to showcase your work and let others know about yourself. It’s like an evergreen platform for your projects, case studies, and information about you. In addition, it’s one of the best ways to express your personality, experience, and capabilities. Having your own website means customers are always able to find you and if interested, reach out for you. If you don’t have an online presence nowadays, you are behind the times. 😉 A portfolio is a great way for photographers, designers, developers and a wide range of artists to present their work online. It lets you reflect your identity through your works – photos, graphic design, sketches, etc.",
        authorName: "Joy Kemunto",
        cover: "assets/images/one.png",
        createdOn:"June 24th 2022",
        authorAvatar: '/assets/images/jif.jpg',
    },
    {
        id: 2,
        title: "How to view my Portfolio",
        category: "School",
        subCategory: ["interview", "ux", "creativity"],
        description: "A portfolio website is a unique way to showcase your work and let others know about yourself. It’s like an evergreen platform for your projects, case studies, and information about you. In addition, it’s one of the best ways to express your personality, experience, and capabilities. Having your own website means customers are always able to find you and if interested, reach out for you. If you don’t have an online presence nowadays, you are behind the times. 😉 A portfolio is a great way for photographers, designers, developers and a wide range of artists to present their work online. It lets you reflect your identity through your works – photos, graphic design, sketches, etc.",
        authorName: "Joy Kemunto",
        cover: "assets/images/kid.jpg",
        createdOn:"June 24th 2022",
        authorAvatar: '/assets/images/jif.jpg',
    },
    {
        id: 3,
        title: "How to view my Portfolio",
        category: "Multitasking",
        subCategory: ["interview", "ux", "creativity"],
        description: "A portfolio website is a unique way to showcase your work and let others know about yourself. It’s like an evergreen platform for your projects, case studies, and information about you. In addition, it’s one of the best ways to express your personality, experience, and capabilities. Having your own website means customers are always able to find you and if interested, reach out for you. If you don’t have an online presence nowadays, you are behind the times. 😉 A portfolio is a great way for photographers, designers, developers and a wide range of artists to present their work online. It lets you reflect your identity through your works – photos, graphic design, sketches, etc.",
        authorName: "Joy Kemunto",
        cover: "assets/images/man.jpg",
        createdOn:"June 24th 2022",
        authorAvatar: '/assets/images/jif.jpg',
    },
    {
        id: 4,
        title: "How to view my Portfolio",
        category: "Deployment",
        subCategory: ["interview", "ux", "creativity"],
        description: "A portfolio website is a unique way to showcase your work and let others know about yourself. It’s like an evergreen platform for your projects, case studies, and information about you. In addition, it’s one of the best ways to express your personality, experience, and capabilities. Having your own website means customers are always able to find you and if interested, reach out for you. If you don’t have an online presence nowadays, you are behind the times. 😉 A portfolio is a great way for photographers, designers, developers and a wide range of artists to present their work online. It lets you reflect your identity through your works – photos, graphic design, sketches, etc.",
        authorName: "Joy Kemunto",
        cover: "assets/images/phar.jpg",
        createdOn:"June 24th 2022",
        authorAvatar: '/assets/images/jif.jpg',
    },
    {
        id: 5,
        title: "How to view my Portfolio",
        category: "Artifacts",
        subCategory: ["interview", "ux", "creativity"],
        description: "A portfolio website is a unique way to showcase your work and let others know about yourself. It’s like an evergreen platform for your projects, case studies, and information about you. In addition, it’s one of the best ways to express your personality, experience, and capabilities. Having your own website means customers are always able to find you and if interested, reach out for you. If you don’t have an online presence nowadays, you are behind the times. 😉 A portfolio is a great way for photographers, designers, developers and a wide range of artists to present their work online. It lets you reflect your identity through your works – photos, graphic design, sketches, etc.",
        authorName: "Joy Kemunto",
        cover: "assets/images/pen.jpg",
        createdOn:"June 24th 2022",
        authorAvatar: '/assets/images/jif.jpg',
    },
    {
        id: 6,
        title: "How to view my Portfolio",
        category: "Studio",
        subCategory: ["interview", "ux", "creativity"],
        description: "A portfolio website is a unique way to showcase your work and let others know about yourself. It’s like an evergreen platform for your projects, case studies, and information about you. In addition, it’s one of the best ways to express your personality, experience, and capabilities. Having your own website means customers are always able to find you and if interested, reach out for you. If you don’t have an online presence nowadays, you are behind the times. 😉 A portfolio is a great way for photographers, designers, developers and a wide range of artists to present their work online. It lets you reflect your identity through your works – photos, graphic design, sketches, etc.",
        authorName: "Joy Kemunto",
        cover: "assets/images/studio.jpg",
        createdOn:"June 24th 2022",
        authorAvatar: '/assets/images/jif.jpg',
    },
];
